### PR TITLE
Forward compatebility with ReactPHP packages

### PR DESCRIPTION
**Pull request by WyriHaximus**
:tada:

### CODE REVIEW

**Comment by WyriHaximus** [comment]
I've contacted Travis about the missing build. Will comment here once that has been resolved.

**Comment by WyriHaximus** [comment]
Issues resolved for Travis :tada:

**Comment by WyriHaximus** [comment]
Failing build is due to travis error with PHP 5.3

**Comment by clue** [comment]
Thank you for filing this PR, much appreciated!

I think your suggested changes make perfect sense and now that the `Stdin` and `Stdout` classes are pretty much just dummy wrapper objects, I wonder if it doesn't make more sense to remove them altogether and simply use the base streams instead. What do you think about this?

(Also thanks for looking into the tests, I'll make sure to take care of the legacy PHP tests)

**Comment by clue** [comment]
Unrelated legacy PHP build error has been addressed via #52 :shipit:

**Comment by WyriHaximus** [comment]
Updated the PR to use streams directly instead of wrapping them in `Stdin` and `Stdout`.

**Comment by mpociot** [comment]
@clue any chance of getting this merged?

**Comment by clue** [comment]
@mpociot Thanks for the friendly ping :) It's near the top of my current TODOs, expect to see a result some time next week :+1:

**Comment by mpociot** [comment]
That’s great, thank you!
I’m using this as one of the dependencies of my BotMan chatbot framework to add support for a CLI chatbot Test environment and I want to update all dependencies to use the latest/stable react versions

**Comment by marktopper** [comment]
@clue, any status on this?

**Comment by clue** [comment]
@marktopper, @WyriHaximus did a very good job at updating dependencies with this PR, but this has been superseded by changes on the `master` in the meantime. I've started picking this up again and will update the status in #50 as soon as time permits :+1:

**Comment by WyriHaximus** [comment]
Cool so closing this in that case 👍 🎉

**Pull request closed without merging**
